# Generated by Django 6.0 on 2025-12-12 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_status', models.BooleanField(default=True)),
                ('main_contact', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_method', models.CharField(choices=[('BACS', 'BACS'), ('BANK TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque')], default='BANK TRANSFER', max_length=15)),
            ],
        ),
    ]
