# Generated by Django 5.2.8 on 2025-12-14 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.area')),
            ],
            options={
                'unique_together': {('area', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=250)),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.subarea')),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.location')),
            ],
            options={
                'unique_together': {('location', 'name')},
            },
        ),
        migrations.AddField(
            model_name='area',
            name='sub_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.sublocation'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('sub_location', 'name')},
        ),
    ]
