# Generated by Django 6.0 on 2025-12-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('storage', '0003_auto_20251219_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(default='e60f4cc5-800a-4cd1-83a4-77dd360becfc', on_delete=django.db.models.deletion.PROTECT, to='storage.subarea'),
        ),
    ]
